### ISSUE TITLE
Enable kustomization directory to be remote

### ISSUE THREAD

**Issue by mcristina422** [kbst/terraform-provider-kustomize#10]
Using krusty has the limitation the the files must be local https://github.com/kbst/terraform-provider-kustomize/blob/f8d142021d82a8e7fc3520785241f174d5fbec2b/data_source_kustomization.go#L52-L68
https://github.com/kubernetes-sigs/kustomize/blob/03cc4e38480104487f067dd20441217f108e7089/api/krusty/kustomizer.go#L43
>Any files referenced by the kustomization must be present in the internal filesystem.

Could https://github.com/kubernetes-sigs/kustomize/blob/master/api/loader/fileloader.go be leveraged to allow the kustomization path to be a remote repo?

**Comment by pst** [comment]
That's a good questions, frankly I don't know the answer. Git remote support in kustomize has a big question mark for me.

The code to determine if a path is a local path or a Git remote, last time I checked, was a bunch of hard coded domain names.

Kustomize also shells out to the git binary to clone the remotes and I doubt a dependency inside a provider on a binary being installed is a good idea.

There seems to be a constant stream of issues upstream with remotes and I am not keen on inheriting this part of kustomize.
