### ISSUE TITLE
webhooks don't support dry-run

### ISSUE THREAD

**Issue by cbek** [kbst/terraform-provider-kustomize#13]
```
Error: Internal error occurred: admission webhook "webhook.tekton.dev" does not support dry run

  on .terraform/modules/eks_zero/common/cluster_services/main.tf line 22, in resource "kustomization_resource" "current":
  22: resource "kustomization_resource" "current" {

Error: Internal error occurred: admission webhook "webhook.tekton.dev" does not support dry run

  on .terraform/modules/eks_zero/common/cluster_services/main.tf line 22, in resource "kustomization_resource" "current":
  22: resource "kustomization_resource" "current" {
```

**Comment by pst** [comment]
Seems this is something that the [Tekton webhook needs to support](https://github.com/tektoncd/pipeline/issues/1513). I don't see anything I can do about this. The provider relies on the server side dry run to do the diff. Without it, there is no reliable way of knowing if a resource can be updated or needs to be recreated.

Resources that are validated by a webhook won't be supported by this provider until the webhook supports dry runs.
