### ISSUE TITLE
Public Mac binaries

### ISSUE THREAD

**Issue by chancez** [kbst/terraform-provider-kustomize#19]
I'm interested in using this provider, but setup is a bit rough due to no mac binaries being published, so I'm having to build these binaries and publish them for our other developers to use to make it so they don't need to do that themselves.

**Comment by pst** [comment]
Hi Chance, happy to hear from you. My goal is to have Github Actions build the binaries and attach them to the releases. See #14 

Currently the provider itself and the release automation around it isn't really mature yet. I manually build the binary and attach it to the releases. I can attach manually built Mac binaries as well for now.

**Comment by pst** [comment]
I've built and attached binaries for the latest release. But I have no way of testing windows or darwin binaries. I only ever tested the linux one.

https://github.com/kbst/terraform-provider-kustomize/releases/tag/v0.1.0-beta.3

**Comment by chancez** [comment]
Sounds good, thanks!
