### ISSUE TITLE
Missing namespace results in 'the server does not allow this method on the requested resource'

### ISSUE THREAD

**Issue by blagerweij** [kbst/terraform-provider-kustomize#20]
We're trying to use the provider with Amazons EKS, which results in the following error:

ResourceCreate: creating '/v1, Resource=configmaps' failed: the server does not allow this method on the requested resource

Running in `--debug` mode does not provide more details, unfortunately. I'm pretty sure it's not related to permissions... Has anyone tested the provider on EKS ?

**Comment by blagerweij** [comment]
Update:
Turns out the above error was related to a missing `namespace: default` directive in the kustomization.yaml file. This is not related to EKS.

**Comment by pst** [comment]
Yes, the provider does not set namespace default unless specified. I think being explicit is better, but I'm open to hear other opinions. In either case, the error message could be better.
