### ISSUE TITLE
admission webhook - does not support dry run

### ISSUE THREAD

**Issue by audriusrudalevicius** [kbst/terraform-provider-kustomize#21]
Is there way to skip dry run for admission webhook?

In my configuration
After running `terraform plan` or `terraform apply`

Getting error:
```
Error: ResourceDiff: admission webhook "...." does not support dry run

  on services/mpi-operator/main.tf line 6, in resource "kustomization_resource" "mpi-operator":
   6: resource "kustomization_resource" "mpi-operator" {
```

**Comment by pst** [comment]
The provider needs the dry-run to work. Only solution I'm aware of would be to make sure the webhook supports the dry-run feature.

This also was a topic with Tekton previously: https://github.com/kbst/terraform-provider-kustomize/issues/13#issuecomment-584312314

I'm open for other solutions if you have one.
