### ISSUE TITLE
Applying a patched Ingress in kustomization fails

### ISSUE THREAD

**Issue by aredridel** [kbst/terraform-provider-kustomize#40]
I get 

```
Error: kustomizationBuild: Kustomizer Run for path 'jitsi' failed: no matches for OriginalId networking.k8s.io_v1beta1_Ingress|~X|jitsi-ingress; no matches for CurrentId networking.k8s.io_v1beta1_Ingress|~X|jitsi-ingress; failed to find unique target for patch networking.k8s.io_v1beta1_Ingress|jitsi-ingress
```

Though kubectl can apply the jitsi directory fine on its own.

[jitsi-kustomize.tar.gz](https://github.com/kbst/terraform-provider-kustomize/files/5038462/jitsi-kustomize.tar.gz) has the terraform file and kustomizations.

**Comment by pst** [comment]
I'm getting the same error when using `kustomize build` directly with `v3.8.1`.

```
$ kustomize build jitsi
Error: no matches for OriginalId networking.k8s.io_v1beta1_Ingress|~X|jitsi-ingress; no matches for CurrentId networking.k8s.io_v1beta1_Ingress|~X|jitsi-ingress; failed to find unique target for patch networking.k8s.io_v1beta1_Ingress|jitsi-ingress
$ kustomize version
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}
```

To fix this, specify a namespace for your patch target like this in `jitsi/kustomization.yaml`:

```
patchesJson6902:
  - path: meet-ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: jitsi-ingress
      namespace: jitsi-meet
```

**Comment by aredridel** [comment]
Oh interesting! With `kubectl apply -k` it works fine.

**Comment by aredridel** [comment]
Thank you!

**Comment by pst** [comment]
> Oh interesting! With `kubectl apply -k` it works fine.

Yes, the Kustomize version included with `kubectl` is ancient and there are numerous caveats like this between it and recent versions.
