### ISSUE TITLE
Admission webhooks do not support dry run

### ISSUE THREAD

**Issue by rvaidya** [kbst/terraform-provider-kustomize#44]
I changed labels on my kustomize overlays, and now all of the admission webhooks that were affected are throwing errors on plan:

Error: ResourceDiff: admission webhook "prometheusrulemutate.monitoring.coreos.com" does not support dry run

  on .terraform/modules/cluster_manifests/main.tf line 23, in resource "kustomization_resource" "current":
  23: resource "kustomization_resource" "current" {

**Comment by rvaidya** [comment]
I suppose these should be skipped - but is there a way to temporarily disable dry run as a workaround to get the terraform state clean again?

**Comment by pst** [comment]
I don't immediately know what the best way forward here is. As a workaround you can try removing from and re-importing the resource into your state after modification using kubectl.

**Comment by rvaidya** [comment]
I worked around it using https://github.com/kbst/terraform-provider-kustomize/pull/47 to temporarily disable dry runs until I could clean up the offending resources.

Main issue I ran into was that commonLabels in kustomize will also apply labels to labelSelectors, which wreaks havoc on operators, as resources that are created by operators won't contain the labels so any labelSelectors that were modified by kustomize won't match.

https://github.com/kubernetes-sigs/kustomize/issues/1009

**Comment by pst** [comment]
https://github.com/kbst/terraform-provider-kustomize/pull/51

I added tests and am not able to reproduce this. This may be K8s version or API version dependent.

If you can provide webhook manifests that make the test fail I'm happy to take another look. Otherwise, I'll consider this closed for now. Re-open if you have new info.
