### ISSUE TITLE
Custom resources do not support StrategicMerge patch type

### ISSUE THREAD

**Issue by rvaidya** [kbst/terraform-provider-kustomize#46]
In these commits:

https://github.com/kbst/terraform-provider-kustomize/commit/212c7834bbc091dcfedb73f26cb388cc4bbc9e62
https://github.com/kbst/terraform-provider-kustomize/commit/5a22486341544fb966693a49ddcb71121efaaf50

the patch type was changed to StrategicMergePatchType, however this patch type is not supported for custom resources:  

https://github.com/kubernetes/kubernetes/issues/71024

Despite the above comment being from 2018 I am getting similar errors on stable GKE:

Error: ResourceDiff: ServiceMonitor prometheus-operator prometheus-op-kube-dns the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml

**Comment by pst** [comment]
I suppose an option could be to try a StrategicMerge and if that is denied fall back to the behavior before the mentioned commit.
