### ISSUE TITLE
Request: provide binaries

### ISSUE THREAD

**Issue by lukasmrtvy** [kbst/terraform-provider-kustomize#5]
Hello, can You provide provider binaries as github assets ? Thanks

**Comment by pst** [comment]
The code is too early to provide releases yet. I have a few more things to validate before I can cut the first release. I am aiming to provide binaries once I make releases.

**Comment by pst** [comment]
Made a release and provided binaries: https://github.com/kbst/terraform-provider-kustomize/releases/tag/v0.1.0-beta.0
