### ISSUE TITLE
Feature request: provider raw credentials

### ISSUE THREAD

**Issue by lukasmrtvy** [kbst/terraform-provider-kustomize#6]
Would be great to have:
- support for something like this https://www.terraform.io/docs/providers/kubernetes/index.html#statically-defined-credentials
or
- do not check for `kubeconfig` presence
or 
- abillity to reference whole kubeconfig_raw file like in https://github.com/banzaicloud/terraform-provider-k8s#usage 

Problem is that if You are referencing `kubeconfig` that is created/resolved in same tf plan as `kustomization` provider, it will not work, because providers are loaded first prior to resources, so its not possible to use for example `local_file` resource to create kubeconfig from https://www.terraform.io/docs/providers/azurerm/d/kubernetes_cluster.html#kube_admin_config_raw before `kustomization` provider usage.

Plan will always fail to:
```
Error: open : no such file or directory
```

Thanks

**Comment by pst** [comment]
I agree, configuration through just kubeconfig is limited but the goal of this very early version is to validate if kustomize, the dynamic client-go and terraform can be made to work together.

Going forward, assuming above holds true, more configuration options are definitely needed. I am happy to review/merge pull requests.
